'use client';

import { PageHeader, StateCard } from '@/app/components/page-header';
import { useFetchState } from '@/app/components/use-fetch-state';
import { PipelineRun } from '@/lib/types';
import { formatBytes, formatDateTime } from '@/lib/utils';

export default function ExportsPage() {
  const { data, loading, error } = useFetchState<PipelineRun[]>('/api/pipelines', []);
  const artifacts = data.flatMap((run) => (run.outputArtifacts ?? []).map((artifact) => ({ run, artifact })));

  return (
    <>
      <PageHeader title="Exports" description="Browse and download real output artifacts generated by completed pipeline runs." />
      {loading ? <StateCard message="Loading export artifacts..." /> : error ? <StateCard message={`Unable to load exports: ${error}`} /> : artifacts.length === 0 ? <StateCard message="No exports found. Completed pipeline outputs will appear here." /> : (
        <div className="space-y-2 rounded-xl border border-border bg-panel p-2">{artifacts.map(({ run, artifact }) => <div key={artifact.id} className="grid grid-cols-1 gap-1 rounded-lg border border-border bg-panelAlt p-3 text-sm lg:grid-cols-7"><div>{artifact.filename}</div><div>{artifact.type}</div><div>{artifact.sizeBytes ? formatBytes(artifact.sizeBytes) : '—'}</div><div>{artifact.recordCount ?? '—'} records</div><div>{formatDateTime(run.updatedAt)}</div><div>{run.id.slice(0, 8)}</div><button disabled={!artifact.downloadUrl} className="rounded border border-border px-2 py-1 text-xs disabled:opacity-50">Download</button></div>)}</div>
      )}
    </>
  );
}
