'use client';

import Link from 'next/link';
import { PageHeader, StateCard } from '@/app/components/page-header';
import { useFetchState } from '@/app/components/use-fetch-state';
import { DocumentRecord, OutputArtifact, PipelineRun } from '@/lib/types';
import { formatBytes, formatDateTime } from '@/lib/utils';

export default function ExportsPage() {
  const artifacts = useFetchState<OutputArtifact[]>('/api/artifacts', []);
  const runs = useFetchState<PipelineRun[]>('/api/pipelines', []);
  const documents = useFetchState<DocumentRecord[]>('/api/documents', []);

  return (
    <>
      <PageHeader title="Exports" description="Browse and download real output artifacts generated by completed pipeline runs." />
      {artifacts.loading || runs.loading || documents.loading ? <StateCard message="Loading export artifacts..." /> : artifacts.error || runs.error || documents.error ? <StateCard message={`Unable to load exports: ${artifacts.error ?? runs.error ?? documents.error}`} /> : artifacts.data.length === 0 ? <StateCard message="No exports found. Completed pipeline outputs will appear here." /> : (
        <div className="space-y-2 rounded-xl border border-border bg-panel p-2">{artifacts.data.map((artifact) => {
          const run = runs.data.find((item) => item.id === artifact.pipelineRunId);
          const doc = documents.data.find((item) => item.id === run?.documentId);
          return <div key={artifact.id} className="grid grid-cols-1 gap-1 rounded-lg border border-border bg-panelAlt p-3 text-sm lg:grid-cols-7"><div>{artifact.filename}</div><div>{artifact.type}</div><div>{artifact.sizeBytes ? formatBytes(artifact.sizeBytes) : '—'}</div><div>{artifact.recordCount ?? '—'} records</div><div>{formatDateTime(artifact.createdAt)}</div><div>{doc ? <Link href={`/sources/${doc.id}`} className="underline">{doc.filename}</Link> : run?.id.slice(0, 8)}</div><a href={`/api/artifacts/${artifact.id}/download`} className="rounded border border-border px-2 py-1 text-center text-xs">Download</a></div>;
        })}</div>
      )}
    </>
  );
}
